package main

import (
	"context"
	"encoding/json"
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/qmrkt/resolution-engine/dag"
	"github.com/qmrkt/resolution-engine/executors"
)

const testPresetExecuteTimeout = 30 * time.Second

// TestPresetExecutionEndToEnd runs every resolution-blueprint preset the
// frontend ships through the real DAG engine with deterministic stub
// executors for external dependencies (LLMs, HTTP APIs, human signals,
// gadget child runs). Each preset must walk to a terminal return and emit
// a structured payload containing at least a `status` field.
//
// Fixtures are generated by the SDK and committed at
// testdata/presets/<id>.json. Regenerate via:
//   cd ../question-sdk && npx tsx src/scripts/dump-preset-fixtures.ts
//
// What's asserted per preset:
//   - Blueprint JSON unmarshals cleanly.
//   - engine.Execute returns status=completed (no panic, no failure).
//   - run.Return has a `status` field that is a known terminal value.
//   - The preset's declared output semantics make sense (e.g. success
//     presets prefer an `outcome`; the YOLO-style preset may defer).
//
// What's NOT asserted:
//   - Real LLM or HTTP responses — external calls are stubbed.
//   - Specific prompt text or model selection — schema-only coverage.
func TestPresetExecutionEndToEnd(t *testing.T) {
	fixtureDir := filepath.Join("testdata", "presets")
	entries, err := os.ReadDir(fixtureDir)
	if err != nil {
		t.Fatalf("read fixtures dir %s: %v (did you run dump-preset-fixtures.ts?)", fixtureDir, err)
	}

	var presetIDs []string
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".json") {
			continue
		}
		presetIDs = append(presetIDs, strings.TrimSuffix(e.Name(), ".json"))
	}
	if len(presetIDs) == 0 {
		t.Fatalf("no preset fixtures found in %s", fixtureDir)
	}

	for _, id := range presetIDs {
		id := id
		t.Run(id, func(t *testing.T) {
			raw, err := os.ReadFile(filepath.Join(fixtureDir, id+".json"))
			if err != nil {
				t.Fatalf("read fixture: %v", err)
			}
			var bp dag.Blueprint
			if err := json.Unmarshal(raw, &bp); err != nil {
				t.Fatalf("unmarshal preset %s: %v", id, err)
			}

			// Short-circuit wait nodes so the test suite doesn't actually sleep.
			patchWaitDurations(&bp)

			engine := newPresetTestEngine()

			inputs := map[string]string{
				"market.question":              "Will Bitcoin close above $150,000 before July 2026?",
				"market.outcomes_json":         `["Yes","No"]`,
				"market.resolution_rules":      "Resolve to the most truthful outcome.",
				"market.context_json":          `{"test_mode":true}`,
				"market.sources_json":          `[]`,
				"yolo.allowed_node_types_json": `["api_fetch","llm_call","agent_loop","wait","return","cel_eval","map"]`,
				"yolo.examples_json":           `[]`,
				"yolo.source_packs_json":       `[]`,
			}

			ctx, cancel := context.WithTimeout(context.Background(), testPresetExecuteTimeout)
			defer cancel()

			run, err := engine.Execute(ctx, bp, inputs)
			if err != nil {
				t.Fatalf("engine.Execute(%s): %v", id, err)
			}
			if run.Status != "completed" {
				t.Fatalf("preset %s: run.Status = %q, want completed (error: %s)", id, run.Status, run.Error)
			}
			if len(run.Return) == 0 {
				t.Fatalf("preset %s: empty run.Return", id)
			}
			var payload map[string]any
			if err := json.Unmarshal(run.Return, &payload); err != nil {
				t.Fatalf("preset %s: return payload is not an object: %v (raw=%s)", id, err, string(run.Return))
			}
			status, _ := payload["status"].(string)
			switch status {
			case "success", "cancelled", "deferred", "timeout":
				// all acceptable terminal states for a defined preset
			default:
				t.Fatalf("preset %s: unexpected terminal status=%q payload=%s", id, status, string(run.Return))
			}
		})
	}
}

// newPresetTestEngine wires an engine with real deterministic executors
// (return, cel_eval, validate_blueprint, wait, map) plus stubs for every
// node type that would otherwise talk to an external service.
func newPresetTestEngine() *dag.Engine {
	engine := dag.NewEngine(slog.Default())

	// Real, deterministic executors.
	engine.RegisterExecutor("return", executors.NewReturnExecutor())
	engine.RegisterExecutor("cel_eval", executors.NewCelEvalExecutor())
	engine.RegisterExecutor("wait", executors.NewWaitExecutor())
	engine.RegisterExecutor("map", executors.NewMapExecutor(engine))
	engine.RegisterExecutor(
		"validate_blueprint",
		executors.NewValidateBlueprintExecutor(func(bp dag.Blueprint, raw []byte) executors.BlueprintValidationResult {
			// Accept whatever the preset generates — we're testing the
			// engine wiring, not the static validator (which has its own tests).
			return executors.BlueprintValidationResult{Valid: true}
		}),
	)
	engine.RegisterExecutor("gadget", executors.NewGadgetExecutor(engine, func(bp dag.Blueprint, raw []byte) executors.BlueprintValidationResult {
		return executors.BlueprintValidationResult{Valid: true}
	}))

	// Stubs for anything that would hit an external system.
	engine.RegisterExecutor("api_fetch", &presetStubExec{outputs: map[string]string{
		"status":  "success",
		"outcome": "0",
		"raw":     `{"result":{"winner":"Yes"}}`,
	}})
	engine.RegisterExecutor("llm_call", &presetStubExec{outputs: map[string]string{
		"status":      "success",
		"outcome":     "0",
		"confidence":  "0.92",
		"reasoning":   "Stubbed deterministic judgment.",
		"output_json": `{"outcome":"0","confidence":"0.92","reasoning":"stubbed"}`,
	}})
	engine.RegisterExecutor("agent_loop", &presetAgentLoopStub{})
	// Real await_signal uses `status: responded` when a human judgment arrives;
	// the preset's success edge condition keys off that value.
	engine.RegisterExecutor("await_signal", &presetStubExec{outputs: map[string]string{
		"status":  "responded",
		"outcome": "0",
		"reason":  "Stubbed human signal.",
	}})

	return engine
}

// presetStubExec returns a fixed map of outputs for every invocation.
// Good enough for api_fetch / llm_call / await_signal where the preset
// just needs ANY success payload to progress to its terminal return.
type presetStubExec struct {
	outputs map[string]string
}

func (s *presetStubExec) Execute(_ context.Context, _ dag.NodeDef, _ *dag.Invocation) (dag.ExecutorResult, error) {
	out := make(map[string]string, len(s.outputs))
	for k, v := range s.outputs {
		out[k] = v
	}
	return dag.ExecutorResult{Outputs: out}, nil
}

// presetAgentLoopStub inspects the node's config to emit outputs that
// match the expected output shape for that node's output_mode.
// Supports:
//   - resolution  → {status, outcome, confidence, reasoning, output_json}
//   - structured  → {status, output_json, raw, output.<key>} for every key
//     in output_tool.parameters.properties (so CEL expressions like
//     `results.draft.output_json.blueprint_json` resolve against a real
//     JSON object).
//   - text        → {status, summary, text}
type presetAgentLoopStub struct{}

func (s *presetAgentLoopStub) Execute(_ context.Context, node dag.NodeDef, _ *dag.Invocation) (dag.ExecutorResult, error) {
	cfg, _ := node.Config.(map[string]any)
	mode, _ := cfg["output_mode"].(string)

	switch mode {
	case "structured":
		// Build a JSON object whose keys match the tool's property schema.
		props := extractToolProperties(cfg)
		obj := map[string]any{}
		for key, propType := range props {
			switch key {
			case "blueprint_json":
				// Minimal valid child blueprint so any downstream validate +
				// gadget step can parse it.
				obj[key] = childBlueprintJSON
			default:
				obj[key] = stubValueForType(propType)
			}
		}
		rawJSON, _ := json.Marshal(obj)
		outputs := map[string]string{
			"status":      "success",
			"output_json": string(rawJSON),
			"raw":         string(rawJSON),
		}
		for k, v := range obj {
			switch vv := v.(type) {
			case string:
				outputs["output."+k] = vv
			default:
				enc, _ := json.Marshal(vv)
				outputs["output."+k] = string(enc)
			}
		}
		return dag.ExecutorResult{Outputs: outputs}, nil

	case "resolution":
		rawJSON := `{"status":"success","outcome":"0","confidence":"0.92","reasoning":"stub"}`
		return dag.ExecutorResult{Outputs: map[string]string{
			"status":      "success",
			"outcome":     "0",
			"confidence":  "0.92",
			"reasoning":   "stub",
			"output_json": rawJSON,
		}}, nil

	default:
		return dag.ExecutorResult{Outputs: map[string]string{
			"status":  "success",
			"summary": "stub",
			"text":    "stub",
		}}, nil
	}
}

// extractToolProperties digs into config.output_tool.parameters.properties
// and returns a map of property name → declared JSON Schema type.
func extractToolProperties(cfg map[string]any) map[string]string {
	tool, _ := cfg["output_tool"].(map[string]any)
	params, _ := tool["parameters"].(map[string]any)
	props, _ := params["properties"].(map[string]any)
	result := make(map[string]string, len(props))
	for name, spec := range props {
		specMap, ok := spec.(map[string]any)
		if !ok {
			continue
		}
		if t, ok := specMap["type"].(string); ok {
			result[name] = t
		}
	}
	return result
}

func stubValueForType(t string) any {
	switch t {
	case "string":
		return "stub"
	case "array":
		return []any{}
	case "object":
		return map[string]any{}
	case "number", "integer":
		return 0
	case "boolean":
		return false
	default:
		return "stub"
	}
}

// childBlueprintJSON is a minimal, valid child blueprint returned by the
// YOLO-style draft/redteam/repair stubs so the `gadget` executor can run
// it to completion without hitting any external services.
var childBlueprintJSON = mustMarshal(map[string]any{
	"id":      "stub-child",
	"version": 1,
	"nodes": []map[string]any{
		{
			"id":   "done",
			"type": "return",
			"config": map[string]any{
				"value": map[string]any{"status": "success", "outcome": "0"},
			},
		},
	},
	"edges": []map[string]any{},
})

func mustMarshal(v any) string {
	b, err := json.Marshal(v)
	if err != nil {
		panic(fmt.Sprintf("mustMarshal: %v", err))
	}
	return string(b)
}

// patchWaitDurations rewrites every wait node to run instantly so the
// test doesn't actually sleep.
func patchWaitDurations(bp *dag.Blueprint) {
	for i, node := range bp.Nodes {
		if node.Type != "wait" {
			continue
		}
		cfg, _ := node.Config.(map[string]any)
		if cfg == nil {
			continue
		}
		cfg["duration_seconds"] = 0
		bp.Nodes[i].Config = cfg
	}
}
